title: Alban Steff - Data Scientist
description: Let's bring AI further.

online_presence:
  show_online_presence: true
  kaggle_url: https://www.kaggle.com/albansteff
  linkedin_url: https://www.linkedin.com/in/alban-steff-260ab715b/

github:
  is_project_page: true
  repository_url: https://github.com/albansteff/albansteff.github.io/
  repository_name: albansteff.github.io
  owner_name: Alban Steff
  owner_url: https://github.com/albansteff/
  
theme: jekyll-theme-cayman
