remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Alban Steff - Data Science projects
description: A selection of wonderful projects.

markdown: kramdown
kramdown:
    math_engine: katex
